### ISSUE TITLE
feature request : updated date

### ISSUE THREAD

**Issue by Neospiro** [FichteFoll/InsertDate#22]
Hi,

Working with a lot of text pieces that are stored in database and duplicated in files, I would like to follow the age of a text block.
Could you add a feature like a snippet with date that could be automaticaly updated when a keystroke or a save is triggered ?

this could be <:[27/07/2015 10:26]:> or anything...

Thank you.

**Comment by FichteFoll** [comment]
Are you looking for something like https://github.com/FichteFoll/InsertDate#snippet-macros? You can bind that to a key stroke with the `run_macro_file` command.

Alternatively, you might want to check out a different plugin that automatically updates file headers, such as one of these: https://packagecontrol.io/search/header.
