### ISSUE TITLE
InsertDate suddenly stopped working

### ISSUE THREAD

**Issue by RonJeffries** [FichteFoll/InsertDate#24]
Today when I started Sublime, InsertDate has stopped working. The console log shows that the key strokes are generating the right calls, insert_date_panel and so on. None of them do anything: the panel never shows up, the prompt window never opens, and the ones with default formats do not insert anything.

I removed InsertDate and installed it with no change. I was getting log errors from ruby and rubytest and have disabled those, so now my python console is clean. It's just that nothing happens.

I hope you'll get this and have some advice. Thanks!

**Comment by FichteFoll** [comment]
Could you post your entire console log after trying to call one or multiple insert date commands?

**Comment by RonJeffries** [comment]
Thanks. I turned on log commands. As you can see, there are no messages. Nothing happened elsewhere: the panel didn't open, the prompt line didn't open, nothing got inserted.

=========
loaded 1104 snippets
Package Control: Skipping automatic upgrade, last run at 2015-08-21 09:31:08, next run at 2015-08-21 10:31:08 or after
Traceback (most recent call last):
  File "./sublime_plugin.py", line 195, in on_modified
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 194, in <lambda>
  File "./distraction_free_mode.py", line 23, in on_modified
  File "./distraction_free_mode.py", line 12, in on_distraction_free
AttributeError: 'Window' object has no attribute 'settings'

// i started inserting dates here:

>>> sublime.log_commands(True)
command: drag_select {"event": {"button": 1, "x": 404.8046875, "y": 287.5546875}}
command: insert_date
no command for selector: noop:

// oops, typed bad sequence, so I looked up the good ones:

command: show_overlay {"overlay": "command_palette"}
command: open_file {"file": "${packages}/InsertDate/Default ($platform).sublime-keymap"}
command: drag_select {"event": {"button": 1, "x": 271.87890625, "y": 669.8515625}}

// nothing happened when I typed these:

command: insert_date_prompt
command: insert_date_panel
command: insert_date

// preparing to copy console

command: drag_select {"event": {"button": 1, "x": 269.0390625, "y": 628.27734375}}

**Comment by FichteFoll** [comment]
What about the part before the `loaded 1104 snippets`?

**Comment by RonJeffries** [comment]
That's the first line in the console log when I open it after starting Sublime fresh.

**Comment by RonJeffries** [comment]
If I start it fresh and quickly hit control tick, log contains this:

theme loaded
app ready
pre session restore time: 0.973687
using gamma: 2 (err: 6.9282)
Loading dictionary Packages/Language - English/en_US.dic
Traceback (most recent call last):
  File "./sublime_plugin.py", line 195, in on_modified
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 194, in <lambda>
  File "./distraction_free_mode.py", line 23, in on_modified
  File "./distraction_free_mode.py", line 12, in on_distraction_free
AttributeError: 'Window' object has no attribute 'settings'
startup cache, total files: 125 cache hits: 125
startup time: 1.38423 (package setup was not run)
loaded 1104 snippets
Package Control: No updated packages

I'll see if I can catch more by being faster. Log isn't open on restart ...

**Comment by RonJeffries** [comment]
Got this:

theme loaded
app ready
pre session restore time: 0.853512
using gamma: 2 (err: 6.9282)
Loading dictionary Packages/Language - English/en_US.dic
Traceback (most recent call last):
  File "./sublime_plugin.py", line 195, in on_modified
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 194, in <lambda>
  File "./distraction_free_mode.py", line 23, in on_modified
  File "./distraction_free_mode.py", line 12, in on_distraction_free
AttributeError: 'Window' object has no attribute 'settings'
startup cache, total files: 125 cache hits: 125
startup time: 1.26157 (package setup was not run)
loaded 1104 snippets
Package Control: Skipping automatic upgrade, last run at 2015-08-21 10:31:51, next run at 2015-08-21 11:31:51 or after

**Comment by RonJeffries** [comment]
I appreciate your looking at this: it's almost certainly not your problem, but I'm hoping you can spot what's happening. I haven't changed any package control stuff in ages, other than removing rspect and ruby after this started happening, to see if that would help.

**Comment by FichteFoll** [comment]
Do you perhaps have multiple Sublime Text windows? If yes, check all of them since newer windows do not percieve the old console log.
There are many lines missing.

**Comment by RonJeffries** [comment]
Ah. In fact I had a million windows hiding away somewhere. Doing it again really clean:

Still a very empty console ...
======
>>> sublime.log_commands(True)
command: drag_select {"event": {"button": 1, "x": 300.2265625, "y": 83.078125}}
command: insert_date
command: insert_date
command: drag_select {"event": {"button": 1, "x": 236.90625, "y": 624.578125}}
command: drag_select {"event": {"button": 1, "x": 806.765625, "y": 638.046875}}

**Comment by RonJeffries** [comment]
misunderstood instructions about checking old windows, sorry. anyway the above is a clean start from no windows.

**Comment by FichteFoll** [comment]
I found a bug (2 actually) while testing the most recent release on my ST2 version. You most likely ran into that, although the lack of a proper console print is weird. I could clearly see a traceback of where the exception occured, also coupled with many other debug lines that every ST version prints on every start.

**Comment by RonJeffries** [comment]
ah. perhaps i'm using console wrong. it doesn't auto open when i start ST. anyway maybe you've found the issue. please let me know if/when you push an update.

relatedly: what are your thoughts on going to ST3? I've been holding off from fear of a difficult upgrade.

**Comment by FichteFoll** [comment]
It never auto opens, but one window must contain the above snippet, you just need to crawl all of them to see which window opened first.

Update pushed via 1543700fd40f69b006c7d7abb8a7e2837c8567ab, should be available on package control in <1h.

I recommend everyone to use ST3, no excuses. It's just so much better.

**Comment by RonJeffries** [comment]
Thanks. I mistakenly closed them. Sounds like you found it anyway.
Also thanks for your thoughts on ST3. I suppose I have to buckle down and get it. Just concerned about getting it configured to my liking again. I have no idea what all I've done.

Thanks again!

**Comment by FichteFoll** [comment]
If you copy over the User folder you should be good 99% of the time. Unless you developed your own packages, everything should have been placed in the User folder.

Package Control will automatically download the packages you had installed because that is saved in `User/Package Control.sublime-settings`.

**Comment by RonJeffries** [comment]
Ah, didn't know that. I'll give it a go soon. Thanks!

**Comment by RonJeffries** [comment]
works, thanks!
