### ISSUE TITLE
Please explain how to configure a keyboard shortcut

### ISSUE THREAD

**Issue by GrouchyGaijin** [FichteFoll/InsertDate#32]
OK, I feel stupid, but can you please tell me exactly how to configure a keyboard shortcut to insert the ISO date in Sublime Text 3?

I have added:
`// iso date (YYYY-MM-DD)
  { "keys": ["ctrl+shift+f5", "ctrl+shift+d"],
    "command": "insert_date",
    "args": {"format": "%Y-%m-%d"} }`

To my Default (Linux) sublime-keymap - User file, but "ctrl+shift+f5" does not do anything.
What exactly am I doing incorrectly?

Thank you,

GG

**Comment by FichteFoll** [comment]
You have to press both key chords in succession. First, <kbd>Ctrl+Shift+F5</kbd> and then <kbd>Ctrl+Shift+D</kbd>.

**Comment by GrouchyGaijin** [comment]
Ahhh I see said the blind man - thank you.
