### ISSUE TITLE
InsertDate don't use system tzdata

### ISSUE THREAD

**Issue by mgurevin** [FichteFoll/InsertDate#34]
InsertDate plugin keeps the required pytz package in installed directory. Therefore that not affected on updating the system timezones. For example, my country changed transition but the plugin was not affected.

My workaround for this reason:
```bash
cp /usr/share/zoneinfo/Turkey ~/.config/sublime-text-3/Packages/pytz/all/pytz/zoneinfo/Europe/Istanbul
cp /usr/share/zoneinfo/Turkey ~/.config/sublime-text-3/Packages/pytz/all/pytz/zoneinfo/Asia/Istanbul
cp /usr/share/zoneinfo/Turkey ~/.config/sublime-text-3/Packages/pytz/all/pytz/zoneinfo/Turkey
```

**Comment by FichteFoll** [comment]
I solved this by updating https://github.com/packagecontrol/pytz from 2015.4 to 2016.7. Running "Package Control: Satisfy Dependencies" in about an hour and restarting ST should fix it for you.
